name: CD

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Deploy
        uses: ./
        with:
          username: UlianaDzigil
          password: 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
          remote_url: https://github.com/UlianaDzigil/one-html-page-challenge.git





